// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKL7aXyo-9m-nVXP7v4oub4CPnvmPiYWw',
    appId: '1:224717357913:web:e0e384b6da59b44b690248',
    messagingSenderId: '224717357913',
    projectId: 'models-5fd9f',
    authDomain: 'models-5fd9f.firebaseapp.com',
    storageBucket: 'models-5fd9f.appspot.com',
    measurementId: 'G-R905WW59MP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfxcm-RJO9xsyUJaeC159M3HCxxOyq-Ik',
    appId: '1:224717357913:android:1b1b70caa3acf2c8690248',
    messagingSenderId: '224717357913',
    projectId: 'models-5fd9f',
    storageBucket: 'models-5fd9f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_t7QW49-fedBDb3-LjFlO9FUabXNTfj4',
    appId: '1:224717357913:ios:567cad4a036847e3690248',
    messagingSenderId: '224717357913',
    projectId: 'models-5fd9f',
    storageBucket: 'models-5fd9f.appspot.com',
    iosBundleId: 'com.example.models',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_t7QW49-fedBDb3-LjFlO9FUabXNTfj4',
    appId: '1:224717357913:ios:fbe673c00d24ec8d690248',
    messagingSenderId: '224717357913',
    projectId: 'models-5fd9f',
    storageBucket: 'models-5fd9f.appspot.com',
    iosBundleId: 'com.example.models.RunnerTests',
  );
}
